# "THE BEER-WARE LICENSE" (Revision 42):
# <robin.hahling@gw-computing.net> wrote this file. As long as you retain this
# notice you can do whatever you want with this stuff. If we meet some day, and
# you think this stuff is worth it, you can buy me a beer in return.
# Robin Hahling

require 'net/http'

module Jekyll
  # Remotely fetch a markdown file.
  class RemoteMarkdownTag < Liquid::Tag
    def initialize(tag_name, url, tokens)
      super
      @url = url
    end

    def render(context)
      uri = URI(context[@url.strip])

      res = Net::HTTP.get_response(uri)
      fail 'resource unavailable' unless res.is_a?(Net::HTTPSuccess)

      text = res.body.force_encoding("UTF-8")

      # Remove header and preamble from autogenerated dbus doc
      lines = text.split(/\n/)
      lines.slice!(0,6)
      text = lines.join("\n")

      context.registers[:site].find_converter_instance(
        Jekyll::Converters::Markdown
      ).convert(text)
    end
  end
end

Liquid::Template.register_tag('remote_markdown', Jekyll::RemoteMarkdownTag)
